services:
  postgres:
    image: postgres:18-alpine
    container_name: aws-image-uploader-database
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev

    container_name: aws-image-uploader-frontend

    ports:
      - "4200:4200"

    volumes:
      - ./apps/frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    
    env_file:
      - ./apps/backend/.env

    container_name: aws-image-uploader-backend

    ports:
      - "3000:3000"

    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres-data: